# GeyserPerServerPacks configuration file.

# Which servers should have per-server packs? Add the server names here.

servers:
# This would be the name of the server(s) in your proxy config.
# - "lobby"
# - "example"
