name: Build
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: gradle:8-jdk17
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Gradle Build
        run: gradle shadowJar
      - name: Modrinth publishing
        run: gradle modrinth